[workspace]
members = ["htmx-ssr"]
#default-members = ["htmx-ssr"]
resolver = "2"

[workspace.dependencies]
htmx-ssr = { path = "./htmx-ssr" }

anyhow = "1"
askama = { version = "0.12", features = ["with-axum"] }
askama_axum = { version = "0.4" }
axum = "0.7"
listenfd = "1"
http = "1"
netdev = "0.31"
serde = { version ="1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
