[package]
name = "htmx-ssr"
description = "HTMX server-side rendering framework for Rust, based on Axum."
version = "0.1.0"
edition = "2021"
authors = ["Julien Kauffmann"]
repository = "https://github.com/ereOn/htmx-ssr.rs"
license-file = "LICENSE"
keywords = ["htmx", "ssr", "web", "html", "axum"]
categories = ["web-programming"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "htmx_ssr"

[dependencies]
